name: vou
description: "VOU - Voucher for you"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.2.1
  sentry_flutter: ^8.12.0
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.2.2
  google_fonts: ^6.2.1
  bootstrap_icons: ^1.11.3
  font_awesome_flutter: ^10.8.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  loading_animation_widget: ^1.3.0
  ticket_clippers: ^0.0.8
  shake: ^1.0.1
  sensors_plus: ^3.0.3
  rive: ^0.13.20
  go_router: ^14.6.3
  get_it: ^8.0.3
  hydrated_bloc: ^9.1.0
  universal_platform: ^1.1.0
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.4
  flutter_tts: ^4.2.1
  socket_io_client: ^3.0.2
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.10
  very_good_analysis: ^4.0.0
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.2
  mockito: ^5.0.17
  http_mock_adapter: ^0.6.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - assets/configs/
    - .env
flutter_native_splash:
  color: "#FF5630"
  image: assets/images/vou.png
  android: true
  ios: true
  web: false