name: main
on:
  pull_request:
    branches:
      - main
      - stage

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - run: flutter pub get

      - run: flutter clean

      - run: flutter build ios --release --no-codesign

      - name: Archive Files
        run: zip -r archive.zip build/ios/iphoneos/Runner.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: archive.zip

  upload_to_drive:
    name: Upload to Google Drive
    runs-on: ubuntu-latest
    needs: build_ios
    steps:
      - name: Get Branch Name
        id: branch
        run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ios-build

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.CREDENTIALS }}
          filename: "archive.zip"
          folderId: ${{ secrets.MAINFOLDERID }}
          name: "${{ needs.build_ios.outputs.branch }}_app_${{ needs.build_ios.outputs.date }}.app"
          overwrite: "true"